### ISSUE TITLE
IDE showing errors on non existent getters/setters methods

### ISSUE THREAD

**Issue by ameagol** [Saka7/spring-boot-angular4-boilerplate#8]
<img width="878" alt="screen shot 2018-04-25 at 11 06 54" src="https://user-images.githubusercontent.com/8441124/39251083-cf6afea8-4878-11e8-9baa-ea2e698b38bf.png">

**Comment by ihor-sakayliuk** [comment]
Which IDE do you use? For IntelliJ there is a [lombok plugin](https://plugins.jetbrains.com/plugin/6317-lombok-plugin).

**Comment by Saka7** [comment]
Which IDE do you use? For IntelliJ there is a [lombok plugin](https://plugins.jetbrains.com/plugin/6317-lombok-plugin).

**Comment by ameagol** [comment]
after create the methods, the errors gone, I have to test now

**Comment by lealceldeiro** [comment]
@ameagol you shouldn't have to write the methods since lombok will do that for you when the project is compiled. This project has lombok in its dependencies (see https://github.com/Saka7/spring-boot-angular4-boilerplate/blob/master/backend/build.gradle). What you should do is to add a plugin for your IDE which recognizes and processes the lombok annotations. In StackOveflow you can check some posts might be useful to you: https://stackoverflow.com/questions/22310414/how-to-configure-lombok-in-eclipse-luna and https://stackoverflow.com/questions/3418865/cannot-make-project-lombok-work-on-eclipse-helios/3425327#3425327

**Comment by ameagol** [comment]
Thank you, @lealceldeiro  that's was a quite dummy issue, forget to create the get/setters. Just wasn't sure how lombok should proceed!
